package org.dromara.semirisk.monolith;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;

@Service
public class RiskDatabase {
    private final JdbcTemplate jdbcTemplate;
    private final ObjectMapper objectMapper;

    public RiskDatabase(JdbcTemplate jdbcTemplate, ObjectMapper objectMapper) {
        this.jdbcTemplate = jdbcTemplate;
        this.objectMapper = objectMapper;
    }

    @PostConstruct
    public void init() {
        jdbcTemplate.execute("""
            create table if not exists risk_store_state (
              state_key varchar(64) primary key,
              payload clob not null,
              updated_at timestamp not null
            )
            """);
        jdbcTemplate.execute("""
            create table if not exists semirisk_users (
              user_id bigint generated by default as identity primary key,
              username varchar(64) not null unique,
              email varchar(128),
              password_hash varchar(512) not null,
              role varchar(16) not null,
              status varchar(16) not null,
              created_at timestamp not null,
              updated_at timestamp not null
            )
            """);
        jdbcTemplate.execute("""
            create table if not exists semirisk_tokens (
              token varchar(64) primary key,
              user_id bigint not null,
              role varchar(16) not null,
              expires_at timestamp not null,
              created_at timestamp not null
            )
            """);
    }

    public RiskStore.SaveState loadState() {
        List<String> rows = jdbcTemplate.query(
            "select payload from risk_store_state where state_key = 'main'",
            (rs, rowNum) -> rs.getString(1)
        );
        if (rows.isEmpty()) {
            return null;
        }
        try {
            return objectMapper.readValue(rows.get(0), RiskStore.SaveState.class);
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to read risk store from database", ex);
        }
    }

    public void saveState(RiskStore.SaveState state) {
        try {
            String payload = objectMapper.writeValueAsString(state);
            int updated = jdbcTemplate.update(
                "update risk_store_state set payload = ?, updated_at = ? where state_key = 'main'",
                payload,
                Instant.now()
            );
            if (updated == 0) {
                jdbcTemplate.update(
                    "insert into risk_store_state(state_key, payload, updated_at) values('main', ?, ?)",
                    payload,
                    Instant.now()
                );
            }
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to save risk store to database", ex);
        }
    }
}
